apiVersion: v2
name: kube-green
description: kube-green helm chart
icon: https://raw.githubusercontent.com/kube-green/kube-green/main/logo/logo.svg

type: application

version: 0.7.29-rc.1
appVersion: "0.7.29-rc.1"
